### ISSUE TITLE
Automatic YAML file generation

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#12]
After the mapping has been established, comments as well as possible domains for properties and classes can be extracted from the ontology automatically

**Comment by pdatascience** [comment]
E.g.

from `properties_db.yml`:
```
doi:
  p: prism:doi
  comment: has DOI
  domain_includes:
    - fabio:JournalArticle
```

from `classes_db.yml`:
```
Article:
  class: fabio:JournalArticle
  comment: an article in a science journal
  properties_include:
    - rdf:type
    - skos:prefLabel
    - skos:altLabel
    - dc:publisher
```
